AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_code
      Description: "Lambda Function CICD"
      MemorySize: 300
      Timeout: 30
      Role: arn:aws:iam::882956824445:role/service-role/redshift_long_running-role-xpr8wj18
      Environment:
      Variables:
        LANDING_ZONE: govglobal
        STAGE: dev

        
      

# AWSTemplateFormatVersion: '2010-09-09'
# Transform: 'AWS::Serverless-2016-10-31'
# Description: A starter AWS Lambda function.
# Parameters: 
#     IdentityNameParameter: 
#       Type: String
# Resources:
#   helloworldpython3:
#     Type: 'AWS::Serverless::Function'
#     Properties:
#       Handler: lambda_function.lambda_handler
#       Runtime: python3.6
#       CodeUri: lambda_code/ 
#       Description: A starter AWS Lambda function.
#       MemorySize: 128
#       Timeout: 3